### ISSUE TITLE
Perfion connection

### ISSUE THREAD

**Issue by cunka** [Ftujio/PerfionFrontEnd#1]
Did you get this connected to Perfion at all? 
I'm interested in doing this.

**Comment by Ftujio** [comment]
Hi! I am a developer from the Perfion Web GUI team. This was just a design prototype for the new version's design. The current project is elsewhere. If you are a client of Perfion (or you are interested in becoming one) and you want to use the Web GUI when it's released, you can contact this email for more information: support@perfion.com​ .

**Comment by svetuli** [comment]
Hi! I am a developer from the Perfion Web GUI team. This was just a design prototype for the new version's design. The current project is elsewhere. If you are a client of Perfion (or you are interested in becoming one) and you want to use the Web GUI when it's released, you can contact this email for more information: support@perfion.com​ .
